export const COUNTRIES = [
  { name: 'France', code: '+33', flag: '🇫🇷' },
  { name: 'Algérie', code: '+213', flag: '🇩🇿' },
  { name: 'Maroc', code: '+212', flag: '🇲🇦' },
  { name: 'Tunisie', code: '+216', flag: '🇹🇳' },
  { name: 'Royaume-Uni', code: '+44', flag: '🇬🇧' },
  { name: 'Belgique', code: '+32', flag: '🇧🇪' },
  { name: 'Espagne', code: '+34', flag: '🇪🇸' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹' },
  { name: 'Italie', code: '+39', flag: '🇮🇹' },
  { name: 'Suisse', code: '+41', flag: '🇨🇭' },
  { name: 'Luxembourg', code: '+352', flag: '🇱🇺' },
  { name: 'Allemagne', code: '+49', flag: '🇩🇪' },
  { name: 'Canada', code: '+1', flag: '🇨🇦' },
  { name: 'États-Unis', code: '+1', flag: '🇺🇸' },
  { name: 'Mexique', code: '+52', flag: '🇲🇽' },
  { name: 'Argentine', code: '+54', flag: '🇦🇷' },
  { name: 'Brésil', code: '+55', flag: '🇧🇷' },
  { name: 'Australie', code: '+61', flag: '🇦🇺' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦' },
  { name: 'Arabie saoudite', code: '+966', flag: '🇸🇦' },
  { code: '+86', name: 'Chine', flag: '🇨🇳' },
  { code: '+81', name: 'Japan', flag: '🇯🇵' },
  { code: '+82', name: 'Corée du sud', flag: '🇰🇷' },
  { code: '+20', name: 'Egypte', flag: '🇪🇬' }
];
